### ISSUE TITLE
`scheduler build --help` throws a traceback

### ISSUE THREAD

**Issue by alexwlchan** [PyconUK/ConferenceScheduler-cli#11]
Clone from master, install dependencies, get help text:

```console
$ scheduler build --help
Traceback (most recent call last):
  File "/Users/chana/.virtualenvs/tempenv-24291291344a6/bin/scheduler", line 11, in <module>
    load_entry_point('conference-scheduler-cli', 'console_scripts', 'scheduler')()
  File "/Users/chana/.virtualenvs/tempenv-24291291344a6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chana/.virtualenvs/tempenv-24291291344a6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/chana/.virtualenvs/tempenv-24291291344a6/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/chana/.virtualenvs/tempenv-24291291344a6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chana/.virtualenvs/tempenv-24291291344a6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/chana/repos/ConferenceScheduler-cli/src/scheduler/cli.py", line 26, in scheduler
    logging.setup(verbosity)
  File "/Users/chana/repos/ConferenceScheduler-cli/src/scheduler/logging.py", line 20, in setup
    daiquiri.output.File(log_file, level='DEBUG'))
  File "/Users/chana/.virtualenvs/tempenv-24291291344a6/lib/python3.6/site-packages/daiquiri/output.py", line 86, in __init__
    handler = logging.handlers.WatchedFileHandler(logpath)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/handlers.py", line 437, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chana/repos/ConferenceScheduler-cli/solution/scheduler.log'
```

😞

Python 3.6.1.

**Comment by drvinceknight** [comment]
Can you `mkdir solution` in root?

**Comment by meatballs** [comment]
you'll probably find the solution dir already exists but there's no log file. For now, just touch `solution/scheduler.log` and I'll have a look at this if things ever die down a bit...
